name: Deploy gateway-service (prod) to Cloud Run

on:
  push:
    branches: [prod]
    paths:
      - 'apps/gateway/**'
      - '.github/workflows/gateway-deploy-prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: legal-platform-466208

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/legal-platform-466208/legal-platform-artifacts/gateway-service:prod ./apps/gateway
          docker push europe-west1-docker.pkg.dev/legal-platform-466208/legal-platform-artifacts/gateway-service:prod

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gateway-service-prod \
            --image=europe-west1-docker.pkg.dev/legal-platform-466208/legal-platform-artifacts/gateway-service:prod \
            --project=legal-platform-466208 \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=auth-service-sa@legal-platform-466208.iam.gserviceaccount.com \
            --set-env-vars "AUTH_SERVICE_URL=https://auth-service-prod-423226444985.europe-west1.run.app,CASE_SERVICE_URL=https://case-service-prod-423226444985.europe-west1.run.app" \
            --set-secrets "INTERNAL_SECRET=INTERNAL_SECRET_PROD:latest"
